### PR TITLE
Added bot detection bundle to prevent link checkers from triggering a double opt in

### PR DESCRIPTION
**Pull request by bildschirmartist**
### Description

In my experience, link checkers often trigger the double opt-in and the website visitor then receives a false error message. To prevent this, I have integrated bot detection.

---

### What is the purpose of this pull request? 

- [ ] Bug fix
- [x] New Feature
- [ ] Documentation update
- [ ] Other

### CODE REVIEW

**Comment by bildschirmartist** [comment]
Hi @cgoIT ,
any chance you could take a look at my PR at short notice? Alternatively, I would take care of another solution that works for me. 
Many thanks in advance and best regards

**Comment by cgoIT** [comment]
Hi @bildschirmartist,

I think I understand the changes you made, but to be honest... I don't see where this problem can arise. The link is part of an email. Which "link checkers" do you mean that could cause such a problem?

btw.: to be able to merge the PR please make sure that all the checks from the build-tools will not fail.

**Comment by bildschirmartist** [comment]
Hi @cgoIT,
First of all: The build-tools check is now working, sorry about that.

We work a lot in the area of B2B marketing. Many companies use technologies such as “Microsoft Defender for Office 365”. When a link is clicked within an email, it is first checked by a link checker (real time verification) and blocked in an emergency. This triggers the DOI, but also invalidates the token. The actual visitor therefore receives a corresponding error message (Invalid token), which leads to confusion.

By integrating bot detection, the DOI would only be executed by the actual visitor.

**Comment by cgoIT** [comment]
Hi @bildschirmartist,

I had a look on your PR. It looks good from a functional perspective. But I can't add it to my composer json. If I do so I get an error while warming up the container (tested it on Contao 5).

```
In CheckExceptionOnInvalidReferenceBehaviorPass.php line 119:
                                                                                                                                                                   
  The service "Cgoit\LeadsOptinBundle\Controller\Module\LeadsOptInModule" has a dependency on a non-existent service "BugBuster\BotDetection\ModuleBotDetection".
```

I think the problem is, that the ModuleBotDetection is not exported as a service. I added a patch that should fix the problem. Could you please try to apply the patch and check if your solution is still working.

And could you please use conventional commits (something like `feat: added bot detection to prevent token confirmation by mistake`. Doing so, release-please will pick up the correct next version number for the release.

[feat__added_bot_detection_to_prevent_token_confirmation_by_mistake.patch](https://github.com/user-attachments/files/17009335/feat__added_bot_detection_to_prevent_token_confirmation_by_mistake.patch)

**Comment by bildschirmartist** [comment]
Hi @cgoIT,
thanks for your check and your fix.
In my development environment, the service `BugBuster\BotDetection\ModuleBotDetection` was instantiated via another extension, so that I did not get the error displayed in the warmup.
Now everything should actually work.

**Pull request merged**
